# Generated by Django 3.0.8 on 2020-07-05 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.CharField(default='', max_length=100)),
                ('additionalCode', models.CharField(default='', max_length=100)),
                ('manufacturer', models.CharField(default='', max_length=100)),
                ('markOwner', models.CharField(default='', max_length=100)),
                ('countryCode', models.CharField(default='', max_length=100)),
                ('countryName', models.CharField(default='', max_length=100)),
                ('additionalInfo', models.CharField(default='', max_length=100)),
                ('bodyType', models.CharField(default='', max_length=100)),
                ('model', models.CharField(default='', max_length=100)),
                ('engineCapacity', models.CharField(default='', max_length=100)),
                ('engineKW', models.CharField(default='', max_length=100)),
                ('color', models.CharField(default='', max_length=100)),
                ('year', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
